branch-defaults:
  master:
    environment: who-poc
    group_suffix: null
global:
  application_name: who-bbg-vis
  branch: null
  default_ec2_keyname: aws-eb
  default_platform: Python 2.7
  default_region: eu-west-2
  instance_profile: null
  no-verify-ssl: true
  platform_name: null
  platform_version: null
  profile: eb-cli
  repository: null
  sc: git
  workspace_type: Application
